### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by humanitiesclinic** [cwnu-airlab/NLTKo#3]
Hi

May I have assistance on installing this package? Please look at the error I keep on getting:

$ git config --global http.sslVerify false
Users-MacBook-Pro-6:~ user$ pip install git+https://github.com/cwnu-airlab/NLTKo
Collecting git+https://github.com/cwnu-airlab/NLTKo
  Cloning https://github.com/cwnu-airlab/NLTKo to /private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-req-build-usnjn0eb
  Running command git clone --filter=blob:none --quiet https://github.com/cwnu-airlab/NLTKo /private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-req-build-usnjn0eb
  Resolved https://github.com/cwnu-airlab/NLTKo to commit 0b686609ff65575a6aec822297c923ea6b74c29c
  Preparing metadata (setup.py) ... done
Collecting safetensors
  Downloading safetensors-0.4.0-cp39-cp39-macosx_10_7_x86_64.whl (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.7/439.7 KB 928.3 kB/s eta 0:00:00
Requirement already satisfied: torch in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nltk==1.2.4) (2.1.1)
Collecting transformers
  Downloading transformers-4.35.2-py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 3.7 MB/s eta 0:00:00
Collecting datasets
  Downloading datasets-2.15.0-py3-none-any.whl (521 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 521.2/521.2 KB 3.5 MB/s eta 0:00:00
Collecting faiss-cpu==1.7.3
  Downloading faiss_cpu-1.7.3-cp39-cp39-macosx_10_9_x86_64.whl (5.6 MB)
     ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/5.6 MB 4.4 MB/s eta 0:00:02
ERROR: Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(chunk_amt)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    # and allows the garbage collector to do it's thing normally.
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    "has been disabled. Check the permissions and owner of "
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    if running_under_virtualenv():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 339, in run
    )
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    limit_how_complex_resolution_can_be = 200000
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    return True
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    ),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    identifier=name,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    )
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    name=name,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
    # download_info may miss the archive_info.hashes field.
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    def __str__(self) -> str:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    # Provide HashError the underlying ireq that caused it. This
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
    version=version,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    self._prepare_linked_requirement(req, parallel_builds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
    for req in reqs:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 214, in unpack_url
    """Prepares a Requirement"""
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url
    download: Downloader,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/network/download.py", line 146, in __call__
    with open(filepath, "wb") as content_file:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py", line 304, in _rich_progress_bar
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    self._fp.close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    'content-encoding' header.
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Users-MacBook-Pro-6:~ user$ pip install git+https://github.com/cwnu-airlab/NLTKo
Collecting git+https://github.com/cwnu-airlab/NLTKo
  Cloning https://github.com/cwnu-airlab/NLTKo to /private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-req-build-j9zf4r9u
  Running command git clone --filter=blob:none --quiet https://github.com/cwnu-airlab/NLTKo /private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-req-build-j9zf4r9u
  Resolved https://github.com/cwnu-airlab/NLTKo to commit 0b686609ff65575a6aec822297c923ea6b74c29c
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      <string>:7: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
      /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9: No module named pip
      Traceback (most recent call last):
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/tmp1_k6kyf3', '--quiet', 'numpy>=1.10']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 662, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-89e45own/overlay/lib/python3.9/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/tmp1_k6kyf3', '--quiet', 'numpy>=1.10']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Users-MacBook-Pro-6:~ user$ git config --global http.sslVerify false
Users-MacBook-Pro-6:~ user$ pip install git+https://github.com/cwnu-airlab/NLTKo
Collecting git+https://github.com/cwnu-airlab/NLTKo
  Cloning https://github.com/cwnu-airlab/NLTKo to /private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-req-build-bsefx40q
  Running command git clone --filter=blob:none --quiet https://github.com/cwnu-airlab/NLTKo /private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-req-build-bsefx40q
  Resolved https://github.com/cwnu-airlab/NLTKo to commit 0b686609ff65575a6aec822297c923ea6b74c29c
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      <string>:7: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
      /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9: No module named pip
      Traceback (most recent call last):
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/tmp3echb8f9', '--quiet', 'numpy>=1.10']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 636, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
        File "/private/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/pip-build-env-qx9an1_f/overlay/lib/python3.9/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/05/rn0kgvkj6zbcgrnh4cyx8gyh0000gn/T/tmp3echb8f9', '--quiet', 'numpy>=1.10']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Users-MacBook-Pro-6:~ user$ python -m pip --version
pip 23.3.1 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)
Users-MacBook-Pro-6:~ user$ type pip
pip is hashed (/Library/Frameworks/Python.framework/Versions/3.9/bin/pip)

**Comment by leeyenaaa** [comment]
Hello! Please try pip install nltkor and let me know if it works.
